const { execSync } = require('child_process');
const { Redirect } = require('../models');

const NGINX_CONF = '/etc/nginx/da-redirects.conf';
const WEB_ROOT   = '/home/digitalaura.temp/public_html';

// Extract path from a URL or return as-is if already a path
function toPath(url) {
  try {
    if (url.startsWith('http://') || url.startsWith('https://')) {
      return new URL(url).pathname;
    }
  } catch {}
  return url.startsWith('/') ? url : '/' + url;
}

async function writeNginxConf() {
  try {
    const redirects = await Redirect.findAll({ where: { is_active: true } });
    const lines = ['# Auto-generated by Digital Aura admin panel — DO NOT EDIT\n'];
    const seen = new Set();
    for (const r of redirects) {
      const fromPath = toPath(r.from_url);
      if (seen.has(fromPath)) continue; // skip duplicates
      seen.add(fromPath);
      const code = r.redirect_type === '302' ? '302' : '301';
      lines.push(`location = ${fromPath} {\n    return ${code} ${r.to_url};\n}\n`);
    }
    require('fs').writeFileSync(NGINX_CONF, lines.join('\n'), 'utf8');
    execSync('nginx -t && nginx -s reload', { stdio: 'pipe' });
    console.log(`[redirect] nginx conf updated — ${seen.size} rules`);
  } catch (err) {
    console.error('[redirect] nginx conf write failed:', err.message);
  }
}

exports.getAll = async (req, res) => {
  try {
    const redirects = await Redirect.findAll({ order: [['createdAt', 'DESC']] });
    res.json({ success: true, data: redirects });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
};

exports.create = async (req, res) => {
  try {
    const { from_url, to_url, redirect_type = '301', is_active = true } = req.body;
    if (!from_url || !to_url)
      return res.status(400).json({ success: false, message: 'from_url and to_url are required' });
    const redirect = await Redirect.create({ from_url, to_url, redirect_type, is_active });
    await writeNginxConf();
    res.status(201).json({ success: true, data: redirect });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
};

exports.update = async (req, res) => {
  try {
    const redirect = await Redirect.findByPk(req.params.id);
    if (!redirect) return res.status(404).json({ success: false, message: 'Not found' });
    await redirect.update(req.body);
    await writeNginxConf();
    res.json({ success: true, data: redirect });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
};

exports.remove = async (req, res) => {
  try {
    const redirect = await Redirect.findByPk(req.params.id);
    if (!redirect) return res.status(404).json({ success: false, message: 'Not found' });
    await redirect.destroy();
    await writeNginxConf();
    res.json({ success: true });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
};

// Legacy Express middleware — kept for /api/ route redirects only
exports.handleRedirects = async (req, res, next) => {
  try {
    const redirects = await Redirect.findAll({ where: { is_active: true } });
    const reqPath = req.path;
    const match = redirects.find(r => toPath(r.from_url) === reqPath);
    if (match) return res.redirect(parseInt(match.redirect_type), match.to_url);
    next();
  } catch {
    next();
  }
};
