/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GoogleAdsAgencyAhmedabadRouteImport } from './routes/google-ads-agency-ahmedabad'
import { Route as IndexRouteImport } from './routes/index'

const GoogleAdsAgencyAhmedabadRoute =
  GoogleAdsAgencyAhmedabadRouteImport.update({
    id: '/google-ads-agency-ahmedabad',
    path: '/google-ads-agency-ahmedabad',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/google-ads-agency-ahmedabad': typeof GoogleAdsAgencyAhmedabadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/google-ads-agency-ahmedabad': typeof GoogleAdsAgencyAhmedabadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/google-ads-agency-ahmedabad': typeof GoogleAdsAgencyAhmedabadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/google-ads-agency-ahmedabad'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/google-ads-agency-ahmedabad'
  id: '__root__' | '/' | '/google-ads-agency-ahmedabad'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GoogleAdsAgencyAhmedabadRoute: typeof GoogleAdsAgencyAhmedabadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/google-ads-agency-ahmedabad': {
      id: '/google-ads-agency-ahmedabad'
      path: '/google-ads-agency-ahmedabad'
      fullPath: '/google-ads-agency-ahmedabad'
      preLoaderRoute: typeof GoogleAdsAgencyAhmedabadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GoogleAdsAgencyAhmedabadRoute: GoogleAdsAgencyAhmedabadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
